knp_paginator:
  page_range: 5
  remove_first_page_param: true
  default_options:
    page_name: page
    sort_field_name: sort
    sort_direction_name: direction
    distinct: true
    filter_field_name: filterField
    filter_value_name: filterValue
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
    rel_links: '@KnpPaginator/Pagination/rel_links.html.twig'
    sortable: '@KnpPaginator/Pagination/bootstrap_v5_bi_sortable_link.html.twig'
    filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig'
